export interface TutorialStep {
  id: string;
  targetSelector: string;
  message: string;
  position: 'top' | 'bottom' | 'left' | 'right';
}

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'skill-allocation-edit',
    targetSelector: '[data-tutorial-id="skill-allocation-edit"]',
    message:
      '加点序列。0123分别表示被动、主动、一武、二武。中括号表示平行加点，即需要根据实际情况抉择加点顺序；小括号表示需要留加点（如莉莉、罗菲2级被动）；减号表示一般不升这级（如苏蕊三级跳舞）。示例：01(0)1[10]22-2',
    position: 'bottom',
  },
  {
    id: 'skill-description-edit',
    targetSelector: '[data-tutorial-id="skill-description-edit"]',
    message:
      '技能描述。可使用[文字](注释)来标记注释；可使用{总伤害}来表示非固定伤害，网站会将其自动拆分为基础伤害和角色增伤；类似地，可使用{_总墙缝伤害}来表示对墙缝的伤害；',
    position: 'bottom',
  },
  {
    id: 'skill-description-edit-continue',
    targetSelector: '[data-tutorial-id="skill-description-edit"]',
    message:
      '此外，可使用{名称/别名}来引用其他角色、角色技能、知识卡、特技、道具或文档，如{剑客泰菲}、{剑菲}将生成指向剑客泰菲页面的链接。',
    position: 'bottom',
  },
  {
    id: 'skill-video-url-edit',
    targetSelector: '[data-tutorial-id="skill-video-url-edit"]',
    message:
      '视频链接。点击后显示/隐藏视频链接输入框。对于B站上的视频，可以在网址后添加"?t=时间"表示视频开始播放的时间点（单位为s，精确到0.1）。如https://www.bilibili.com/video/BV1xK4y1d7f5?t=61.5，此处对应1分1.5秒。', // video link is generated by AI
    position: 'bottom',
  },
  {
    id: 'character-preview',
    targetSelector: '[data-tutorial-id="character-preview"]',
    message: '预览按钮。点击后可预览非编辑模式下的信息显示。',
    position: 'bottom',
  },
  {
    id: 'character-export',
    targetSelector: '[data-tutorial-id="character-export"]',
    message:
      '保存按钮。点击后会将角色的数据复制到剪切板中并下载文件。网站存储不保证稳定，请多多保存。',
    position: 'bottom',
  },
  {
    id: 'character-tutorial',
    targetSelector: '[data-tutorial-id="character-tutorial"]',
    message: '教程按钮。点击后可重新查看本功能指引。',
    position: 'bottom',
  },
];

const TUTORIAL_SEEN_KEY = 'hasUserSeenCharacterDetailsTutorial';

export const hasUserSeenCharacterDetailsTutorial = (): boolean => {
  if (typeof window === 'undefined') {
    return true; // Assume seen on server-side rendering
  }
  return localStorage.getItem(TUTORIAL_SEEN_KEY) === 'true';
};

export const markCharacterDetailsTutorialAsSeen = (): void => {
  if (typeof window !== 'undefined') {
    localStorage.setItem(TUTORIAL_SEEN_KEY, 'true');
  }
};

export const resetCharacterDetailsTutorial = (): void => {
  if (typeof window !== 'undefined') {
    localStorage.removeItem(TUTORIAL_SEEN_KEY);
  }
};
