import 'server-only';

import { NextResponse } from 'next/server';

import { SITE_NAME, SITE_URL } from '@/constants/seo';

import {
  getMediaWikiCatalog,
  getMediaWikiPageById,
  lookupMediaWikiPage,
  searchMediaWikiCatalog,
  type MediaWikiCatalog,
  type MediaWikiPage,
} from './catalog';

type UnknownRecord = Record<string, unknown>;

type TitleTarget = Readonly<{
  page: MediaWikiPage;
  canonical: boolean;
}>;

type CatalogIndex = Readonly<{
  catalog: MediaWikiCatalog;
  byId: ReadonlyMap<number, MediaWikiPage>;
  byTitle: ReadonlyMap<string, TitleTarget>;
}>;

type ResolvedPage = Readonly<{
  page: MediaWikiPage;
  alias: boolean;
  normalizedTitle: string;
}>;

type QueryPage = Readonly<{
  page: MediaWikiPage | null;
  requestedTitle: string;
  normalizedTitle: string;
  missingKey: string;
  alias: boolean;
}>;

const MAX_BATCH_SIZE = 15;
const MAX_TITLE_LENGTH = 500;
const MAX_SEARCH_LENGTH = 200;
const MAX_EXTRACT_CHARS = 1000;
const MAX_SEARCH_RESULTS = 10;

const PUBLIC_CACHE = 'public, max-age=60, s-maxage=60, stale-while-revalidate=300';
const SITEINFO_CACHE = 'public, max-age=43200, s-maxage=43200, stale-while-revalidate=86400';
const NO_CACHE = 'no-store, max-age=0';

const API_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Accept, Content-Type, User-Agent',
  Vary: 'Origin',
} as const;

function jsonResponse(payload: unknown, cacheControl: string): NextResponse {
  return NextResponse.json(payload, {
    headers: {
      ...API_HEADERS,
      'Cache-Control': cacheControl,
    },
  });
}

function mediaWikiError(code: string, info: string, cacheControl = NO_CACHE): NextResponse {
  return jsonResponse({ error: { code, info } }, cacheControl);
}

function normalizeTitle(value: string): string {
  return value
    .normalize('NFC')
    .replace(/_/g, ' ')
    .replace(/[\u00a0\u1680\u180e\u2000-\u200b\u202f\u205f\u3000]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function titleKey(value: string): string {
  return normalizeTitle(value).toLocaleLowerCase('zh-CN');
}

function absoluteHttpUrl(value: string | undefined): string | undefined {
  if (!value?.trim()) return undefined;
  try {
    const url = new URL(value, SITE_URL);
    return url.protocol === 'http:' || url.protocol === 'https:' ? url.toString() : undefined;
  } catch {
    return undefined;
  }
}

function createCatalogIndex(catalog: MediaWikiCatalog): CatalogIndex {
  const byTitle = new Map<string, TitleTarget>();

  // pagesByTitle already contains the catalog's effective lookup policy: an
  // ambiguous name points at a synthetic disambiguation page. Do not rebuild
  // this policy from the source pages, since doing so would lose that choice.
  for (const [title, page] of catalog.pagesByTitle) {
    const key = titleKey(title);
    if (key) byTitle.set(key, { page, canonical: titleKey(page.title) === key });
  }

  // Keep the handler tolerant of a catalog generated by an older build that
  // did not expose every alias in pagesByTitle.
  for (const page of catalog.pages) {
    const canonicalKey = titleKey(page.title);
    if (canonicalKey && !byTitle.has(canonicalKey)) {
      byTitle.set(canonicalKey, { page, canonical: true });
    }
    for (const alias of page.aliases) {
      const aliasKey = titleKey(alias);
      if (aliasKey && !byTitle.has(aliasKey)) byTitle.set(aliasKey, { page, canonical: false });
    }
  }

  return { catalog, byId: catalog.pagesById, byTitle };
}

async function loadCatalog(): Promise<MediaWikiCatalog> {
  return getMediaWikiCatalog();
}

function resolveTitle(index: CatalogIndex, rawTitle: string): ResolvedPage | null {
  const normalizedTitle = normalizeTitle(rawTitle);
  if (!normalizedTitle) return null;

  const target = index.byTitle.get(titleKey(normalizedTitle));
  if (target) {
    return {
      page: target.page,
      alias: !target.canonical,
      normalizedTitle,
    };
  }

  // The public helper retains the exact catalog normalization semantics. Use
  // it as a final fallback for Unicode variants not represented in our map.
  const exact = lookupMediaWikiPage(index.catalog, normalizedTitle);
  if (!exact) return null;
  return {
    page: exact,
    alias: titleKey(exact.title) !== titleKey(normalizedTitle),
    normalizedTitle,
  };
}

function lookupPageById(index: CatalogIndex, rawId: string): MediaWikiPage | null {
  if (!/^\d+$/.test(rawId)) return null;
  const pageid = Number(rawId);
  if (!Number.isSafeInteger(pageid) || pageid <= 0) return null;
  return getMediaWikiPageById(index.catalog, pageid) ?? index.byId.get(pageid) ?? null;
}

function isValidPageId(value: string): boolean {
  if (!/^\d+$/.test(value)) return false;
  const pageid = Number(value);
  return Number.isSafeInteger(pageid) && pageid > 0;
}

function parsePipeValues(
  raw: string | null,
  parameter: string
): { values?: string[]; error?: NextResponse } {
  if (raw === null) {
    return { error: mediaWikiError('missingparam', `The "${parameter}" parameter must be set.`) };
  }

  const values = raw.split('|');
  if (values.length > MAX_BATCH_SIZE) {
    return {
      error: mediaWikiError(
        'toomanyvalues',
        `The "${parameter}" parameter accepts at most ${MAX_BATCH_SIZE} values.`
      ),
    };
  }
  if (values.some((value) => value.length > MAX_TITLE_LENGTH)) {
    return { error: mediaWikiError('invalidtitle', `A value in "${parameter}" is too long.`) };
  }
  return { values };
}

function parsePageQueries(
  params: URLSearchParams,
  index: CatalogIndex
): { results?: QueryPage[]; error?: NextResponse } {
  const titlesPresent = params.has('titles');
  const pageidsPresent = params.has('pageids');
  if (titlesPresent && pageidsPresent) {
    return {
      error: mediaWikiError(
        'invalidparammix',
        'The "titles" and "pageids" parameters cannot be used together.'
      ),
    };
  }
  if (!titlesPresent && !pageidsPresent) {
    return {
      error: mediaWikiError('missingparam', 'The "titles" or "pageids" parameter must be set.'),
    };
  }

  if (titlesPresent) {
    const parsed = parsePipeValues(params.get('titles'), 'titles');
    if (parsed.error) return { error: parsed.error };
    if (!parsed.values) {
      return { error: mediaWikiError('missingparam', 'The "titles" parameter must be set.') };
    }
    return {
      results: parsed.values.map((requestedTitle, indexInBatch) => {
        const resolved = resolveTitle(index, requestedTitle);
        return {
          page: resolved?.page ?? null,
          requestedTitle,
          normalizedTitle: resolved?.normalizedTitle ?? normalizeTitle(requestedTitle),
          missingKey: String(-(indexInBatch + 1)),
          alias: resolved?.alias ?? false,
        };
      }),
    };
  }

  const parsed = parsePipeValues(params.get('pageids'), 'pageids');
  if (parsed.error) return { error: parsed.error };
  if (!parsed.values) {
    return { error: mediaWikiError('missingparam', 'The "pageids" parameter must be set.') };
  }

  const results: QueryPage[] = [];
  for (const [indexInBatch, requestedId] of parsed.values.entries()) {
    if (!isValidPageId(requestedId)) {
      return { error: mediaWikiError('invalidpageid', `Invalid page ID "${requestedId}".`) };
    }
    const page = lookupPageById(index, requestedId);
    results.push({
      page,
      requestedTitle: page?.title ?? requestedId,
      normalizedTitle: page?.title ?? requestedId,
      missingKey: String(-(indexInBatch + 1)),
      alias: false,
    });
  }
  return { results };
}

function clampExtract(value: string, params: URLSearchParams): string {
  const raw = params.get('exchars');
  if (raw === null || !/^\d+$/.test(raw)) return value;
  const requested = Number(raw);
  if (!Number.isSafeInteger(requested)) return value;
  const length = Math.min(Math.max(requested, 1), MAX_EXTRACT_CHARS);
  return value.slice(0, length);
}

function toPagePayload(page: MediaWikiPage, params: URLSearchParams): UnknownRecord {
  return {
    pageid: page.pageid,
    ns: 0,
    title: page.title,
    fullurl: page.fullUrl,
    canonicalurl: page.canonicalUrl,
    // This facade intentionally exposes optional collections as empty values
    // for every virtual page, keeping AkariBot's old parser predictable.
    extract: clampExtract(page.extract, params),
    templates: [],
    langlinks: [],
    pageprops: page.kind === 'disambiguation' ? { disambiguation: '' } : {},
    // MediaWiki normally reserves imageinfo for File pages. AkariBot expects
    // imageinfo[0].url on entity pages, so this compatibility behavior is
    // intentional.
    // AkariBot treats the presence of imageinfo as proof that element zero
    // exists, so omit the property entirely for pages without an image.
    ...(page.imageUrl
      ? {
          imageinfo: [
            {
              url: page.imageUrl,
              descriptionurl: page.fullUrl,
              descriptionshorturl: page.fullUrl,
            },
          ],
        }
      : {}),
  };
}

function addQueryPage(
  pages: Record<string, UnknownRecord>,
  query: QueryPage,
  params: URLSearchParams,
  normalized: Array<{ from: string; to: string }>,
  redirects: Array<{ from: string; to: string }>
): void {
  if (query.page) {
    pages[String(query.page.pageid)] = toPagePayload(query.page, params);
    if (query.alias) redirects.push({ from: query.requestedTitle, to: query.page.title });
    if (query.normalizedTitle !== query.requestedTitle) {
      normalized.push({ from: query.requestedTitle, to: query.normalizedTitle });
    }
    return;
  }

  pages[query.missingKey] = {
    ns: 0,
    title: query.normalizedTitle || query.requestedTitle,
    missing: true,
  };
  if (query.normalizedTitle !== query.requestedTitle) {
    normalized.push({ from: query.requestedTitle, to: query.normalizedTitle });
  }
}

function siteInfo(catalog: MediaWikiCatalog): UnknownRecord {
  const mainPage = catalog.pages.find((page) => page.kind === 'main')?.title ?? SITE_NAME;
  return {
    batchcomplete: true,
    query: {
      general: {
        mainpage: mainPage,
        base: `${SITE_URL}/`,
        sitename: SITE_NAME,
        generator: 'tjwiki-mediawiki-compat/1.0',
        logo: absoluteHttpUrl('/icon.png'),
        lang: 'zh-cn',
        dir: 'ltr',
        fallback: 'zh-cn',
        writeapi: false,
        timezone: 'Asia/Shanghai',
        articlepath: '/$1',
        scriptpath: '',
        script: '/index.php',
        server: SITE_URL,
        wikiid: 'tjwiki',
      },
      namespaces: {
        '0': { '*': '', id: 0, case: 'first-letter', content: '' },
      },
      namespacealiases: [],
      interwikimap: [],
      extensions: [{ name: 'TextExtracts' }],
    },
  };
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => {
    switch (character) {
      case '&':
        return '&amp;';
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      case '"':
        return '&quot;';
      case "'":
        return '&#39;';
      default:
        return character;
    }
  });
}

function renderPageBody(page: MediaWikiPage): string {
  if (page.candidates?.length) {
    const candidates = page.candidates
      .map((candidate) => {
        const href = escapeHtml(candidate.fullUrl);
        const title = escapeHtml(candidate.qualifiedTitle);
        const qualifier = candidate.kindDescription
          ? `，${escapeHtml(candidate.kindDescription)}`
          : '';
        const description = candidate.description
          ? `，${escapeHtml(candidate.description)}`
          : qualifier;
        return `<li><a href="${href}" title="${title}">${title}</a>${description}</li>`;
      })
      .join('');
    return `<p>${escapeHtml(page.title)}可能指：</p><ul>${candidates}</ul>`;
  }

  const extract = page.extract.trim();
  return extract ? `<p>${escapeHtml(extract).replace(/\n/g, '<br />')}</p>` : '';
}

function parsePage(page: MediaWikiPage, params: URLSearchParams): UnknownRecord {
  const rawProps = params.get('prop');
  const props =
    rawProps === null || rawProps.trim() === '' ? new Set(['text']) : new Set(rawProps.split('|'));
  const body = renderPageBody(page);
  const parsed: UnknownRecord = {
    title: page.title,
    pageid: page.pageid,
  };

  if (props.has('text')) {
    parsed.text = { '*': `<div class="mw-parser-output">${body}</div>` };
  }
  if (props.has('headhtml')) {
    const html = `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><title>${escapeHtml(page.title)}</title></head><body class="mediawiki ltr ns-0 ns-subject"><div class="mw-parser-output">${body}</div></body></html>`;
    parsed.headhtml = { '*': html };
  }
  if (props.has('sections')) {
    parsed.sections = page.sections.map((section) => ({
      toclevel: 1,
      level: String(section.level),
      line: section.line,
      number: section.index,
      index: section.index,
      fromtitle: page.title,
      byteoffset: 0,
      anchor: section.anchor,
    }));
  }
  return parsed;
}

function searchAction(
  catalog: MediaWikiCatalog,
  params: URLSearchParams
): UnknownRecord | NextResponse {
  const rawSearch = params.get('srsearch');
  if (rawSearch === null || !rawSearch.trim()) {
    return mediaWikiError('missingparam', 'The "srsearch" parameter must be set.');
  }
  if (rawSearch.length > MAX_SEARCH_LENGTH) {
    return mediaWikiError('invalidparam', 'The "srsearch" parameter is too long.');
  }

  const rawWhat = params.get('srwhat') ?? 'text';
  if (rawWhat !== 'text' && rawWhat !== 'title' && rawWhat !== 'nearmatch') {
    return mediaWikiError('invalidparam', `Invalid value for "srwhat": ${rawWhat}.`);
  }

  const rawNamespace = params.get('srnamespace') ?? '0';
  if (rawNamespace !== '0' && rawNamespace !== '*') {
    return mediaWikiError('invalidparam', 'Only namespace 0 and * are supported.');
  }

  const rawLimit = params.get('srlimit');
  const parsedLimit = rawLimit === null ? MAX_SEARCH_RESULTS : Number(rawLimit);
  const limit = Number.isFinite(parsedLimit)
    ? Math.min(Math.max(Math.trunc(parsedLimit), 1), MAX_SEARCH_RESULTS)
    : MAX_SEARCH_RESULTS;
  const rows = searchMediaWikiCatalog(catalog, normalizeTitle(rawSearch), {
    what: rawWhat,
    limit,
    namespace: rawNamespace === '*' ? '*' : 0,
  });

  return {
    batchcomplete: true,
    query: {
      searchinfo: { totalhits: rows.length },
      search: rows.map((row) => ({
        ns: 0,
        title: row.title,
        pageid: row.pageid,
        size: row.page.extract.length,
        wordcount: row.wordcount,
        snippet: escapeHtml(row.snippet),
        timestamp: new Date(0).toISOString(),
      })),
    },
  };
}

function randomAction(
  catalog: MediaWikiCatalog,
  params: URLSearchParams
): UnknownRecord | NextResponse {
  const namespace = params.get('rnnamespace') ?? '0';
  if (namespace !== '0' && namespace !== '*') {
    return mediaWikiError('invalidparam', 'Only namespace 0 and * are supported.', NO_CACHE);
  }
  const page = catalog.articlePages[Math.floor(Math.random() * catalog.articlePages.length)];
  if (!page) return mediaWikiError('notarget', 'No pages are available.', NO_CACHE);
  return {
    batchcomplete: true,
    query: { random: [{ id: page.pageid, ns: 0, title: page.title }] },
  };
}

function queryAction(
  catalog: MediaWikiCatalog,
  index: CatalogIndex,
  params: URLSearchParams
): UnknownRecord | NextResponse {
  const meta = params.get('meta');
  const list = params.get('list');
  if (meta === 'siteinfo') {
    if (list || params.has('titles') || params.has('pageids')) {
      return mediaWikiError('invalidparammix', 'The "meta" and page parameters cannot be mixed.');
    }
    return siteInfo(catalog);
  }
  if (meta) return mediaWikiError('unknown_meta', `Unknown meta module "${meta}".`);
  if (list === 'search') return searchAction(catalog, params);
  if (list === 'random') return randomAction(catalog, params);
  if (list) return mediaWikiError('unknown_list', `Unknown list module "${list}".`);

  const pageQueries = parsePageQueries(params, index);
  if (pageQueries.error) return pageQueries.error;
  if (!pageQueries.results) {
    return mediaWikiError('missingparam', 'A page query parameter must be set.');
  }

  const pages: Record<string, UnknownRecord> = {};
  const normalized: Array<{ from: string; to: string }> = [];
  const redirects: Array<{ from: string; to: string }> = [];
  for (const query of pageQueries.results) {
    addQueryPage(pages, query, params, normalized, redirects);
  }

  return {
    batchcomplete: true,
    query: {
      ...(normalized.length ? { normalized } : {}),
      ...(redirects.length ? { redirects } : {}),
      pages,
    },
  };
}

function parseAction(index: CatalogIndex, params: URLSearchParams): UnknownRecord | NextResponse {
  const pageParam = params.get('page');
  const pageIdParam = params.get('pageid');
  if (pageParam !== null && pageIdParam !== null) {
    return mediaWikiError(
      'invalidparammix',
      'The "page" and "pageid" parameters cannot be used together.'
    );
  }
  if (pageParam === null && pageIdParam === null) {
    return mediaWikiError('missingparam', 'The "page" or "pageid" parameter must be set.');
  }

  const page =
    pageIdParam !== null
      ? lookupPageById(index, pageIdParam)
      : resolveTitle(index, pageParam ?? '')?.page;
  if (!page) return mediaWikiError('missingtitle', 'The requested page could not be found.');

  const props = params.get('prop');
  if (props) {
    const unsupported = props
      .split('|')
      .map((property) => property.trim())
      .filter((property) => property && !['headhtml', 'sections', 'text'].includes(property));
    if (unsupported.length) {
      return mediaWikiError('unknown_prop', `Unknown parse property "${unsupported[0]}".`);
    }
  }
  return { parse: parsePage(page, params) };
}

export async function handleMediaWikiGet(request: Request): Promise<NextResponse> {
  const params = new URL(request.url).searchParams;
  const format = params.get('format');
  if (format && format !== 'json') {
    return mediaWikiError('formatnotsupported', 'Only the JSON format is supported.');
  }

  const action = params.get('action');
  if (!action) return mediaWikiError('unknown_action', 'The "action" parameter is required.');
  if (action !== 'query' && action !== 'parse') {
    return mediaWikiError(
      'unknown_action',
      `Unrecognized value for parameter "action": ${action}.`
    );
  }

  try {
    const catalog = await loadCatalog();
    const index = createCatalogIndex(catalog);
    const result =
      action === 'query' ? queryAction(catalog, index, params) : parseAction(index, params);
    if (result instanceof NextResponse) return result;

    const cacheControl =
      action === 'query' && params.get('meta') === 'siteinfo'
        ? SITEINFO_CACHE
        : action === 'query' && params.get('list') === 'random'
          ? NO_CACHE
          : PUBLIC_CACHE;
    return jsonResponse(result, cacheControl);
  } catch (error) {
    console.error('MediaWiki API catalog failure:', error);
    return mediaWikiError(
      'internal_api_error',
      'The MediaWiki catalog is temporarily unavailable.'
    );
  }
}

export function handleMediaWikiOptions(): NextResponse {
  return new NextResponse(null, {
    status: 204,
    headers: {
      ...API_HEADERS,
      'Access-Control-Max-Age': '43200',
      'Cache-Control': SITEINFO_CACHE,
    },
  });
}
