export const CHARACTER_ROLE_ATTRIBUTE_KEYS = [
  'roleType',
  'physicsType',
  'sex',
  'EnglishName',
  'size',
  'runSpeed',
  'jumpSpeed',
  'jumpHeight',
  'climbSpeed',
  'visionScale',
  'gravity',
  'baseHp',
  'maxHp',
  'hpRecovery',
  'attack',
  'wallDamage',
  'attackRange',
  'attackCooldown',
  'pushCheeseSpeed',
  'initialItem',
  'deformCooldown',
  'shoppingCooldown',
  'shoppingDelay',
] as const;

export type CharacterRoleAttributeKey = (typeof CHARACTER_ROLE_ATTRIBUTE_KEYS)[number];

export const CHARACTER_ROLE_ATTRIBUTE_TOOLTIPS: Readonly<
  Record<CharacterRoleAttributeKey, string>
> = {
  roleType: '角色类型：猫、鼠、特殊角色',
  physicsType: '决定角色是否可进行某些交互，以及交互方式',
  sex: '影响局内语音和塔拉等角色的技能效果',
  EnglishName: '角色的英文译名',
  size: '角色的判定区域大小',
  runSpeed: '横向移动速度；单位：单位长/秒',
  jumpSpeed: '跳跃的初速度；单位：单位长/秒',
  jumpHeight: '根据跳跃速度和重力计算的整数跳跃高度',
  climbSpeed: '持续交互攀爬梯子的基础速度；单位：单位长/秒',
  visionScale: '基础视野缩放倍率；数值越大，实际视野越小',
  gravity: '受到的重力大小',
  baseHp: '初始健康值',
  maxHp: '健康值上限，即“血条”',
  hpRecovery: '健康状态下每秒恢复的健康值',
  attack: '增加对其他角色造成的伤害',
  wallDamage: '增加对墙缝造成的伤害',
  attackRange: '角色的基础攻击范围',
  attackCooldown: '爪刀的冷却时间（命中/未命中）',
  pushCheeseSpeed: '推奶酪速度；单位：%/秒',
  initialItem: '初始手持的道具',
  deformCooldown: '部分角色特殊变形彩蛋的触发冷却',
  shoppingCooldown: '购物后再次购物所需等待的时间',
  shoppingDelay: '角色开始购物至到货所需的时间',
};
