export const CHARACTER_ROLE_ATTRIBUTE_KEYS = [
  'roleType',
  'physicsType',
  'sex',
  'EnglishName',
  'size',
  'runSpeed',
  'jumpSpeed',
  'jumpHeight',
  'climbSpeed',
  'visionScale',
  'gravity',
  'baseHp',
  'maxHp',
  'hpRecovery',
  'attack',
  'wallDamage',
  'attackRange',
  'attackCooldown',
  'pushCheeseSpeed',
  'initialItem',
  'deformCooldown',
  'shoppingCooldown',
  'shoppingDelay',
] as const;

export type CharacterRoleAttributeKey = (typeof CHARACTER_ROLE_ATTRIBUTE_KEYS)[number];

export const CHARACTER_ROLE_ATTRIBUTE_TOOLTIPS: Readonly<
  Record<CharacterRoleAttributeKey, string>
> = {
  roleType: '角色类型：猫、鼠、以及特殊角色',
  physicsType: '物理特质会决定角色是否可进行某些交互，以及实际的交互方式',
  sex: '会影响塔拉等角色技能的实际效果',
  EnglishName: '角色的英文译名',
  size: '角色的判定区域大小，会影响碰撞及部分效果范围判定内容',
  runSpeed: '角色在平地横向移动时的基础速度；单位为“单位长/秒”；1“米”=32“单位长”',
  jumpSpeed: '角色完整纵向跳跃时的初速度；单位为“单位长/秒”；1“米”=32“单位长”',
  jumpHeight: '根据跳跃速度和重力计算的整数跳跃高度',
  climbSpeed: '角色持续交互攀爬梯子时的基础速度；单位为“单位长/秒”',
  visionScale: '决定基础视野范围；数值越大，实际视野越小',
  gravity: '决定角色受到的重力大小',
  baseHp: '角色的初始健康值',
  maxHp: '健康值上限，即“血条”',
  hpRecovery: '每秒恢复的健康值',
  attack: '角色的基础攻击力，会提高对其他角色造成的部分伤害',
  wallDamage: '角色的基础破坏力，会提高对墙缝造成的部分伤害',
  attackRange: '角色的基础攻击范围',
  attackCooldown: '角色进行常规攻击后的冷却时间；未命中与命中可能使用不同数值',
  pushCheeseSpeed: '角色的基础推奶酪速度，已折算为“%/秒”',
  initialItem: '角色初始手持的道具',
  deformCooldown: '部分角色特殊变形彩蛋的内置触发冷却',
  shoppingCooldown: '成功购物后再次购物所需等待的时间',
  shoppingDelay: '角色开始购物至道具到货所需的时间',
};
